### ISSUE TITLE
Feature: position-fallback-bounds - allowing the user to set fallback anchor

### ISSUE THREAD

**Issue by bearcat-msft** [oddbird/css-anchor-positioning#147]
Hi Oddbird, 

I am unable to successfully use [position-fallback-bounds](https://drafts.csswg.org/css-anchor-position/#fallback-bounds) with the polyfill. It works correctly [in this stackblitz](https://stackblitz.com/edit/typescript-c4idvv?file=index.ts) when setting the experimental web platform flag, but not with the polyfill.

position-fallback-bounds allows the user to set which anchoring element they want to define as the bounding element. The defined bounding element is used for calculating against the target element to detect collisions (like in the case of a popover, or when using the popover API). 

Is this something that's already a known issue? Is it feature work that's planned? Thanks.

**Comment by jgerigmeyer** [comment]
@bearcat-msft Thanks for the question! There have been a lot of changes to the spec over the past year (including `position-fallback-bounds`), and unfortunately we haven't had the bandwidth to keep the polyfill up to date with them. I'm cautiously optimistic that we'll be able to make more progress on this in 2024, but honestly unless we find some sponsors to help support this work, its velocity will be somewhat determined by how much time we can dedicate to OSS work.

**Comment by jamesnw** [comment]
I'm closing this, as `position-fallback-bounds` is no longer part of the spec, and we will track overflow management with the position-try syntax in #167.
