### ISSUE TITLE
Floating-ui upgrade to 1.6 (#148) is perhaps worthy of a new `css-anchor-positioning` release to unpkg

### ISSUE THREAD

**Issue by johanrd** [oddbird/css-anchor-positioning#150]
Hi. Great work on a polyfill here! Thanks a lot.

Floating-ui was just updated to `v1.6`, which is a pretty big deal for positioning popovers: Positioning within other top-level content is now supported, e.g. a popover inside a `<dialog>`, see https://github.com/floating-ui/floating-ui/pull/2747

Tested against main now – seems to work well. The latest release of [css-anchor-positioning](https://github.com/oddbird/css-anchor-positioning) on unpkg is 0.3.0, which has floating-ui 1.2. I'd consider PR #148 as a release-worthy improvement.

Thank you

**Comment by jgerigmeyer** [comment]
@johanrd Good idea! I'll do a release this week.

Note that there have been a lot of changes to the spec over the past year, and unfortunately we haven't had the bandwidth to keep the polyfill up to date with them. I'm cautiously optimistic that we'll be able to make more progress on this in 2024, but honestly unless we find some sponsors to help support this work, its velocity will be somewhat determined by how much time we can dedicate to OSS work.

**Comment by jgerigmeyer** [comment]
Released in [v0.0.4](https://github.com/oddbird/css-anchor-positioning/releases/tag/v0.0.4)
