### ISSUE TITLE
Document that `polyfill` returns a promise.

### ISSUE THREAD

**Issue by aigan** [oddbird/css-anchor-positioning#154]
I stumbled on a situation where the polyfill when used in firefox, will remove an input elements focus.
On my computer, the focus can be set about 60ms after the import promise resolved. I need a promise for when it has finished its job so that I can re-apply the focus, or for other actions that will need to use the polyfill.

**Comment by jgerigmeyer** [comment]
@aigan Have you tried importing the [callable `css-anchor-positioning-fn.js` version of the polyfill](https://github.com/oddbird/css-anchor-positioning#configuration)? If you import that build, you can call it directly and `await` the response, which shouldn't resolve until all positioning has been applied. For example:

```html
<script type="module">
  if (!("anchorName" in document.documentElement.style)) {
    const { default: polyfill } = await import("https://unpkg.com/@oddbird/css-anchor-positioning/dist/css-anchor-positioning-fn.js");

    await polyfill();
    console.log("polyfill is done");
  }
</script>
```

**Comment by aigan** [comment]
That does seem to work. 
Didn't see anything about it returning a promise in the README.
