### ISSUE TITLE
[BUG] Anchoring with popover doesn't open the popovers anymore

### ISSUE THREAD

**Issue by GueganVictor** [oddbird/css-anchor-positioning#223]
**Describe the bug**
The popover doesn't open anymore when the polyfill is applied and there's no way to show it unless you disable the polyfill.

**To Reproduce**

1. Go to the [demo website](https://anchor-polyfill.netlify.app/#anchor-positioning-popover)
2. Apply the polyfill on Firefox or Safari on the top left
3. Click on anchor to open the popover
4. Nothing happens, the popover isn't shown

**Expected behavior**
Popover should open anchored to the element

**Browsers tested on**
Any supported version of Firefox or Safari.

**Additional context**
Thank you for your work !

**Comment by jgerigmeyer** [comment]
Thanks for reporting! Fixed in https://github.com/oddbird/css-anchor-positioning/commit/9eb8df8946d20b0008bae8f2bcdaaefce44fa777
