### ISSUE TITLE
`<link>` elements are replaced without all of their attributes

### ISSUE THREAD

**Issue by tuespetre** [oddbird/css-anchor-positioning#242]
https://github.com/oddbird/css-anchor-positioning/blob/f1d3bcc126f62f302e4dbc519224bef3c9dcd035/src/transform.ts#L19
After this line, only the `rel` and `href` attributes are set. I'm sure there be dragons with using `el.cloneNode()` to copy all attribute values outright (event handlers, `integrity`, etc.), but these attributes should definitely be kept if present on the original element:
- `disabled`
- `id`
- `media`
- `title`

**Comment by jgerigmeyer** [comment]
This is released in [v0.3.0](https://github.com/oddbird/css-anchor-positioning/releases/tag/v0.3.0).
