### ISSUE TITLE
[BUG] Vue3 app polyfill does nothing

### ISSUE THREAD

**Issue by rodhoward** [oddbird/css-anchor-positioning#282]
**Describe the bug**
Having loaded the polly fill both via vite bundling and http header methods I can't seem to get it to apply to my achor css.
I'm just not sure if this limitation "dynamically added/removed anchors or targets" applies to my case I supose it does as all elements are dynamically added after page load.

Any hints on how to use it in a framework like Vue3 would be great.

**To Reproduce**
1. Add css anchor tags to vue3 components works great in chrome. 
2. Add polly fill

example css anchor styles I'm using:
```style="position-anchor: --skphuurbho; anchor-name: --arrowskphuurbho; top: anchor(bottom); right: anchor(right);"```
Where the anchor position names are randomly generated as each component is created.

**Expected behavior**
1. Works on Chrome (no poly fill required)
2. Works on Firefox and Safari (polyfill doing its thing)

**Browsers tested on**
Chrome latest (works great)
Firefox 133 (doesn't work polyfill doesn't seem to do anything)

**Additional context**
Working in Ubuntu.

**Comment by jamesnw** [comment]
There could be a few different things happening here- would you be able to make a minimal recreation, perhaps on Codepen with their Vue template?

First, it appears that Vue pre-processes inline styles, and removes any that the browser doesn't support. This is great for prefixing, but not so great here. For example, in this [playground](https://play.vuejs.org/#eNp9kctOwzAQRX9l8CYg9aEKVmlaCVAlYAEIkNh4EyWTR/FLtlOKovw7Y0ctXaDu7Ll37pzR9OzWmNmuQ5ayzBW2NR4c+s6suWql0dZDDxYrGKCyWkJC1oQrrgqtnAfpalgF/TJ5QCE0fGoryovkiqtsPsZREH08SiNyj/QDyJoFOP8jcMVZoYW2KUWUS8hV0Wg7VbnEFKbTSuslZ+u+j2OGIZs3C+rP5idhbMK8I5aqrWdbpxWt0YcRIViaVqB9Mb4lVs5SiErQckL9foo1bzucHOpFg8XXP/Wt24caZ68WHdodcnbUfG5r9KO8eX/GPb2PotRlJ8h9RnxDp0UXGEfbXadKwj7xRdrHeIxW1R9us/eo3GGpABqcQ/RzRge6P7P6H+717Cb2cTWw4Rd3e6vz), if you inspect the `h1`, it will have an `anchor-name` style in Chrome, but not in Safari. 

If you're able to move the styles out of the inline template, perhaps using `anchor-scope`, it may work.

As far as the dynamically removed/added portion- polyfill will apply itself to any elements that are in the DOM when it is applied. If you add additional elements, the polyfill won't know about them yet.

Let us know if it's one of these two issues, or something else. Thanks!

**Comment by rodhoward** [comment]
Hi James,

Thanks for you feedback! I did notice that the styles where missing in firefox I just thought firefox must have removed them I didn't realise inline styles where removed by vue.

Here is a little [Vue SFC Playground](https://play.vuejs.org/#eNp9lEtz2yAQx78K4RJ7JrIyTU+y0+ljfEgPaaftkQuWkESMgIGVY4/H370Letht5Ix9gN0/7G8f6Ei/WLvYtYJmdOVzJy0QL6C1n5iWjTUOyJE4UZITKZ1pyC1Kb0eXNepQStW5GM29T7jOa+MSa7wEabTUFaNLPFCS2c2M0c79zBvBKJGaFCZvG6FhMSzWSsS9h4MS8zk5Mk2GOLM50yemwy832gNpfEUeAx7e/HTbEK7xHwLcMIraVdplhLngBkRjFQeBO0JWhdyRGOOR0Q3Pt5UzrS6S3CjjMlI5flgyGqW9OFfcexRDLRIOwPNaFJjDcMeQcEb4xhvVglgidmfri5KRJCmNWRIwFmXRNtsYANPMl8TJqobRHHfzgBDzCk3hqxQ5riLFcxdAb5NS4c6NapGs75LGPoxUr7KAOiMf7u/tfklq0fE8xC1yHI+x3KfTGWNYrdKL2q4iAC4WZ6yuixNB+3520r6oQ8snaxdcU+UL9ukKhgg4CD0UvaPgcXhKWS1evNE49jEcDq9prFTC/bAhrGc060CCjytlXr9HG7hW3A12xM23E/YXvw82Rn864YXb4bCPPuCuEtC517+fxR7Xo7MxRatQ/Y7zl4jjhYyd7Ct2GLEvdJH2Kb5QfH5//HoPQvshqQAalKeoZxQf9Ld3Uj/jPiw+xnNYUaxi9wVIGm7/q2Pn+PeSax+GwF8DWJ+laavttlpgF9LPpig20hXp9DEcOg9XfEmpEYfREfT0F7EfrKg=) example of the issue and possible wrok around. This example is currently working for me in firefox. However if you remove the class from the two elements then the inline styles will NOT be enough as they are removed.

This doesn't really solve my problem because I'm building components e.g. a dropdown for use anywhere on the parent application. So each of these components needs a unique anchor name.. Hence my random names and the inline styles. 

Thanks again for your quick response hopefully this helps others.

Cheers
Rod

**Comment by jamesnw** [comment]
Thanks for the reproduction! I don't think there's anything we can do at the polyfill level to support inline styles in Vue- they just don't exist at the point we need them.

I think your use case is exactly what `anchor-scope` is for- as long as you can colocate your anchor and anchored item within a wrapper (or can put the anchored item inside the anchor), `anchor-scope` will prevent the algorithm from looking for an anchor outside that scope.

Here's an [example](https://play.vuejs.org/#eNqNVE1T2zAQ/SuLLiQDjoH25CQMlOFAp0MZ2qMvji07IrKkkeQkTMb/vSvJdhMaMp3xQat9+/X8tDtyr9Rk3VCSkJnJNVMWDLWNuk0Fq5XUFnagaQktlFrWcI7Q88GlJH8vGefBl5LcmCgT+VLqSEnDLJOCiSol01SkIpfCWCi0VIXciAfZCAtzl3t0M0ZAcNem6i5T8nReQybwcwnPUjLuQVxmxUtfeg6j8fx2hz2VMDrDsIB/zmqaEmACCpk3NRV20h8eOfW2se+cjseAsTCMMsIqrf9mceADmUDD0lrxzFK0AGaLxlop4C7nLF/NU3Iw1cVFSm7vi2IWB9h/hEQRhrzSWq7p6aj90THkB5rQ24eRBVuDnxCjFlm+qjQWKqJccqkTqHT2PsUEDtqB11EpNYIZjup5228Qqcx5Zgz6NzpTiurD4N5pqV1STQvoD4MQMEPfTn+VQLYwkjeWTjvVCPxrCUTYiXTdeQU4QWaw27m+2nYWY7ljlUOGvSr/Ds1ZtbQL3tApbFhhlwncXF2p7RSW1HkSuPYmFt7tvBLb9njd4dyfZvGePma+AzxMOqq8wKATcmRyqfyQwUbpo9gmwQha/EDGgAOoM10x5O2a1l3cQHin4sBsF/Oxyh5++C8h0EqFf8NDRzk+DqrdmwTgtEReOod2LLn78Dq6KcklsTiTKFk1eTNS4CbxKXEdyFoxTvVP5QqZlCShmPNlnMvNd39ndUMv+/t8SfPVkfs3s3V3KXnR1FC9xsc9+CyyQlGizv3465lu8Tw4a1k0HNEnnK/Uq9CL1MG+oWaw7T2c7/bJLz1caL/N49ZSYfqhXKMO2Xp8SnBHPpwY/W+7XyZffRwyiiyGpRrVmfrAY3AcJvls1br+l9Yqk8RxI9SqmuBfiO9kUSyYLuLjYahiYz/xRaXAdlIyNNr+AQtUJkg=) that shows it working without IDs. 

It also demonstrates the current limitation of the polyfill- when you click "Load Polyfill" it will apply the anchor to each element that is currently present in the dom, but won't add it to new elements.

I don't think there are changes to be made here, so I'll close this out, but link #91 so others can find the examples if they are useful.

**Comment by rodhoward** [comment]
Thanks again and YES anchor-scope is exactly what I need.
