### ISSUE TITLE
`anchor-name` doesn't work when defined in a `style` attribute

### ISSUE THREAD

**Issue by andreubotella** [oddbird/css-anchor-positioning#44]
The `anchor-name` property doesn't seem to work when defined in an element's `style` attribute.

https://codepen.io/andreubotella/pen/JjZYLpR

This polyfill doesn't set any additional styles on the target element, and therefore it shows up below the anchor. Whereas on (canary) Chromium with the `CSSAnchorPosition` feature enabled, it is positioned just right of the "Anchor" text.

Supporting this, together with #45, will allow defining a reusable class for tooltips in a CSS file and allow individual elements to define their anchor names or the anchor to be positioned against using `style` attributes, since this is arguably semantic CSS.

**Comment by andreubotella** [comment]
This is apparently fixed in the repo, but not on the alpha release linked on the readme.

**Comment by jgerigmeyer** [comment]
Fixed in v0.0.1: https://www.npmjs.com/package/@oddbird/css-anchor-positioning
