### ISSUE TITLE
The `anchor()` function doesn't support variables as anchor targets

### ISSUE THREAD

**Issue by andreubotella** [oddbird/css-anchor-positioning#45]
The optional first argument of the `anchor()` function, which is a dashed ident that indicates the anchor target, can be replaced by a custom property: for example, `anchor(var(--anchor) left)`. This variable substitution is not supported in this polyfill.

https://codepen.io/andreubotella/pen/mdKexxX

This polyfill doesn't set any additional styles on the target element, and therefore it shows up below the anchor. Whereas on (canary) Chromium with the `CSSAnchorPosition` feature enabled, it is positioned just right of the "Anchor" text.

Supporting this, together with #44, will allow defining a reusable class for tooltips in a CSS file and allow individual elements to define their anchor names or the anchor to be positioned against using `style` attributes, since this is arguably semantic CSS.

**Comment by andreubotella** [comment]
This is apparently fixed in the repo, but not on the alpha release linked on the readme.

**Comment by jgerigmeyer** [comment]
Fixed in v0.0.1: https://www.npmjs.com/package/@oddbird/css-anchor-positioning

**Comment by andreubotella** [comment]
I closed this issue by mistake – this does not seem to be actually fixed in v0.0.1 or in the main branch of the repo. The codepen in the OP currently throws an exception that will be fixed with #47, but even with that fix applied, it still does not apply any `left` or `top` styles to `.target`. In fact, the `parseAnchorFn` function in parse.ts only accepts identifier tokens as the anchor name.

**Comment by jgerigmeyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow specifying anchor name via CSS custom property.](https://trello.com/c/96CVqhwf/72-allow-specifying-anchor-name-via-css-custom-property)

**Comment by jgerigmeyer** [comment]
@andreubotella Can you take a look at #49 and see if that fixes this issue?
