### ISSUE TITLE
Compatibility with popover polyfill

### ISSUE THREAD

**Issue by morki** [oddbird/css-anchor-positioning#84]
This polyfill seems to be incompatible with https://github.com/oddbird/popover-polyfill
This is unfortunate, because for me, it is the primary use case.

**Comment by jgerigmeyer** [comment]
@morki Can you say more (or better yet, provide a basic repo test case 🙏 ) about specifically how this polyfill isn't compatible with the popover-polyfill? I'm probably missing your use-case, but using the basic local demo page for the popover-polyfill I was able to quickly combine these two polyfills and anchor a popover to another element.

**Comment by jgerigmeyer** [comment]
> The problem seems to be absolute position of anchor or any of its ancesors.

I think that might be correct as per the [spec](https://w3c.github.io/csswg-drafts/css-anchor-position/#acceptable-anchor-element)?

> If el has the same [containing block](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block) as query el, el is not [absolutely positioned](https://w3c.github.io/csswg-drafts/css-position-3/#absolute-position).
>
> If el has a different [containing block](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block) from query el, the last containing block in el’s [containing block chain](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block-chain) before reaching query el’s containing block is not [absolutely positioned](https://w3c.github.io/csswg-drafts/css-position-3/#absolute-position).

But I might be missing something. If you think there's a bug in how this polyfill interprets the spec in regard to determining a valid anchor, please open a new issue. 👍
