### ISSUE TITLE
Absolutely positioned anchor

### ISSUE THREAD

**Issue by morki** [oddbird/css-anchor-positioning#89]
> The problem seems to be absolute position of anchor or any of its ancesors.

I think that might be correct as per the [spec](https://w3c.github.io/csswg-drafts/css-anchor-position/#acceptable-anchor-element)?

> If el has the same [containing block](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block) as query el, el is not [absolutely positioned](https://w3c.github.io/csswg-drafts/css-position-3/#absolute-position).
>
> If el has a different [containing block](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block) from query el, the last containing block in el’s [containing block chain](https://w3c.github.io/csswg-drafts/css-display-4/#containing-block-chain) before reaching query el’s containing block is not [absolutely positioned](https://w3c.github.io/csswg-drafts/css-position-3/#absolute-position).

But I might be missing something. If you think there's a bug in how this polyfill interprets the spec in regard to determining a valid anchor, please open a new issue. 👍

_Originally posted by @jgerigmeyer in https://github.com/oddbird/css-anchor-positioning/issues/84#issuecomment-1456385890_

**Comment by jgerigmeyer** [comment]
@morki I'm having trouble reproducing this in Chrome Canary with `Experimental Web Platform features` enabled. Could you point me to an example or a codepen or something so I can confirm where the polyfill is differing from the Chrome implementation?

**Comment by jgerigmeyer** [comment]
@morki Ah, thank you! I was able to reproduce this now, and I am confident it is fixed in #90, which should be merged and released soon.
